### ISSUE TITLE
Division by zero error

### ISSUE THREAD

**Issue by bbunce** [bbunce/Qsee#15]
When trying to add data to a brand new control after completing the input form you get a division by zero error.

![Screenshot from 2022-02-16 17-43-37](https://user-images.githubusercontent.com/23362494/154332041-2969fc04-ad09-4978-94a7-0e3d76eb1ba8.png)

**Comment by gdoy1** [comment]
Fixed. Moved len(list) check above standard deviation calculation to avoid zero division in empty lists.
